// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuh8QlnS_oJO1pIeACyQgAcYhW-rZg7rs',
    appId: '1:442314911704:web:ac9309924d9529bb598cad',
    messagingSenderId: '442314911704',
    projectId: 'login-register-fa0cd',
    authDomain: 'login-register-fa0cd.firebaseapp.com',
    storageBucket: 'login-register-fa0cd.appspot.com',
    measurementId: 'G-27XHXN0D1X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPWue6kR-DM-YgGoVMeZizuwmp2Zheyfs',
    appId: '1:442314911704:android:0116224921050759598cad',
    messagingSenderId: '442314911704',
    projectId: 'login-register-fa0cd',
    storageBucket: 'login-register-fa0cd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBE5Er970N63y-WkR7q1Sdg2vHlqxk0Qvg',
    appId: '1:442314911704:ios:fc1acfeaad0cb0f2598cad',
    messagingSenderId: '442314911704',
    projectId: 'login-register-fa0cd',
    storageBucket: 'login-register-fa0cd.appspot.com',
    iosBundleId: 'com.example.loginAndRegisterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBE5Er970N63y-WkR7q1Sdg2vHlqxk0Qvg',
    appId: '1:442314911704:ios:276e4efc7e8d7201598cad',
    messagingSenderId: '442314911704',
    projectId: 'login-register-fa0cd',
    storageBucket: 'login-register-fa0cd.appspot.com',
    iosBundleId: 'com.example.loginAndRegisterApp.RunnerTests',
  );
}
